---
# Copyright (c) 2020 Contributors to Smart-Data-Models
# see https://github.com/smart-data-models/dataModel.Building

components:
  schemas:
    InverterDevice:
      $ref: 'https://smart-data-models.github.io/harmonization/InverterDevice/model.yaml#/InverterDevice'
info:
  description: |
    The data model is intended to describe the mechanical, electrical
    characteristics of an Inverter according to *DC - Direct Current
    Information* supplied as input and *AC - Alternating Current Information* 
    returned as output. *Remark*: This Data Model can be used directly as a main
    entity to describe the device [Inverter] or as a sub-entity of the Data
    Model {DEVICE] using a reference by the [refDevice] attribute.
  title: InverterDevice
  version: 1.0.0
openapi: 3.0.0
paths:
  /ngsi-ld/v1/entities:
    get:
      description: Retrieve a set of entities which matches a specific query from an NGSI-LD system
      parameters:
        - in: query
          name: type
          required: true
          schema:
            enum:
              - InverterDevice
            type: string
      responses:
        '200':
          content:
            application/ld+json:
              examples:
                keyvalues:
                  summary: Key-Values Pairs
                  value:
                    - $ref: 'https://smart-data-models.github.io/harmonization/InverterDevice/examples/example.json'
                normalized:
                  summary: Normalized NGSI-LD
                  value:
                    - $ref: 'https://smart-data-models.github.io/harmonization/InverterDevice/examples/example-normalized.jsonld'
          description: OK
      tags:
        - ngsi-ld
tags:
  - description: NGSI-LD Linked-data Format
    name: ngsi-ld
